baseurl = "http://esolia.com/"
title = "eSolia Inc."
contentdir = "content/en"
publishdir = "public/en"
canonifyurls = "false"
copyright = "This work is copyright. All rights reserved by eSolia Inc."
MetaDataFormat = "yaml"
# For RSS only, apparently
languageCode = "en-US"

[author]
    name = "Rick Cogley"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:section/:slug"

[taxonomies]
    tag = "tags"
    topic = "topics"
    series = "series"

[blackfriday]
    plainIdAnchors = true

[params]
    locale = "en-US"
    alternatelocales = ["ja-JP"]
    description = "Website of eSolia Inc. - a Tokyo-based IT Management and support firm."
    keywords = ["Japan","IT","Management","Support","Outsourcing","Helpdesk","Website","Development","Operations"]
    author = "Team eSolia"
    accountableperson = "Rick Cogley"
    entityname = "eSolia Inc."
    # Used when a given page doesn't set its own.
    defaultDescription = "Content by eSolia Inc."
    defaultKeywords = "eSolia"
    ISO8601 = "2006-01-02T15:04:05JST"
    googleAnalytics = "UA-1040233-7"

[[menu.side]]
    name = "Topics"
    identifier = "topics"
    weight = 111

[[menu.side]]
    name = "All Topics"
    identifier = "alltopics"
    url = "/topics"
    parent = "topics"
    weight = 1

[[menu.side]]
    name = "All Tags"
    identifier = "alltags"
    url = "/tags"
    parent = "topics"
    weight = 2

[[menu.side]]
    name = "About eSolia"
    identifier = "aboutesolia"
    url = "/topics/esolia"
    parent = "topics"
    weight = 10

[[menu.side]]
    name = "Services"
    identifier = "ourservices"
    weight = 20
    url = "/topics/services"
    parent = "topics"

[[menu.side]]
    name = "Telephone"
    identifier = "telephone"
    weight = 30
    url = "/topics/telephone"
    parent = "topics"

[[menu.side]]
    name = "Tools"
    identifier = "tools"
    weight = 222

[[menu.side]]
    name = "Zerobin"
    identifier = "zerobin"
    url = "https://zerobin.esolia.com"
    post = "_blank"
    parent = "tools"
    weight = 22

[[menu.side]]
    name = "eSolia Connect"
    identifier = "connect"
    url = "http://connect.esolia.com"
    post = "_blank"
    parent = "tools"
    weight = 33

[[menu.detailfooter1]]
    name = "All Topics"
    identifier = "topics"
    url = "/topics"
    weight = 55

[[menu.homefooter2]]
    name = "Zerobin"
    identifier = "zerobin"
    url = "https://zerobin.esolia.com"
    post = "_blank"
    weight = 22

[[menu.homefooter2]]
    name = "eSolia Connect"
    identifier = "connect"
    url = "http://connect.esolia.com"
    post = "_blank"
    weight = 33

[[menu.homefooter2]]
    name = "All Topics"
    identifier = "topics"
    url = "/topics"
    weight = 44

[[menu.homefooter2]]
    name = "All Tags"
    identifier = "tags"
    url = "/tags"
    weight = 55
